name: Main

on:
  push:
    branches:
      - main

env:
  ACTION_NAME: deploy-helm-gke-action
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/deploy-helm-gke-action

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ github.sha }}
  release-pr:
    name: Maybe create release PR
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      -
        uses: GoogleCloudPlatform/release-please-action@v2
        id: release-please
        with:
          release-type: simple
          package-name: ${{ env.ACTION_NAME }}
          command: release-pr
      -
        name: Get PR branch ref
        uses: actions/github-script@v4
        if: ${{ steps.release-please.outputs.pr }}
        id: pr-data
        env:
          PULL_NUMBER: ${{ steps.release-please.outputs.pr }}
        with:
          script: |-
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: process.env.PULL_NUMBER,
            });
            core.setOutput('branchRef', pr.data.head.ref);
      -
        name: Checkout
        uses: actions/checkout@v2
        if: ${{ steps.release-please.outputs.pr }}
        with:
          ref: ${{ steps.pr-data.outputs.branchRef }}
      -
        name: Reference versioned Docker Hub image
        if: ${{ steps.release-please.outputs.pr }}
        run: |-
          sed --in-place=.bkp "s|image: Dockerfile|image: docker://$GITHUB_REPOSITORY:v${{ github.sha }}|g" action.yml
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "chore: Update Docker Hub image reference to ${{ github.sha }}" -- action.yml || true
          git push || true
  release:
    name: Maybe publish release
    runs-on: ubuntu-latest
    steps:
      -
        uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: simple
          package-name: ${{ env.ACTION_NAME }}
          command: github-release
      -
        uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      -
        name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
